name: Gradle Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 JDK 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # 或者使用 'zulu', 'adopt' 等
        java-version: '17'

    # 缓存 Gradle 构建文件
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 验证 Gradle Wrapper
    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 8.0

    # 编译项目
    - name: Build with Gradle
      run: ./gradlew build

    # 编译 gradle-plugin 模块
    - name: Build Gradle Plugin
      run: ./gradlew :gradle-plugin:build

    # 运行测试
    - name: Run tests
      run: ./gradlew test

    # 上传编译产物
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
            **/build/libs/*.jar
            **/build/outputs/**/*.aar


            
